### ISSUE TITLE
Future schema(s)

### ISSUE THREAD

**Issue by bkspace** [lizkenyon/shopifyQL-example#1]
This looks super cool, thanks for building an example! A couple of questions:

Is there anywhere we can see future schema changes/a roadmap for what's coming next?
Is the reporting functionality in the Shopify admin built on top of ShopifyQL, or will it be in the future? If so, will there eventually be parity by what can be filtered/searched on between the two?

**Comment by lizkenyon** [comment]
If the roadmap will be published the most likely place will be the [developer docs](https://shopify.dev/api/shopifyql).

Follow Shopify on their official social channels, and their blog. That is where new information is released.

**Comment by bkspace** [comment]
Those were the first place I looked - and these were additional questions that arose from that investigation. Thanks anyway, enjoy your day :)
